package com.example.sample

import com.example.sample.groups.appGroup
import com.example.sample.groups.dataGroup
import com.example.sample.groups.featureGroup
import com.example.sample.groups.gradleGroup
import com.example.sample.groups.testingGroup
import com.example.sample.groups.toolGroup
import com.example.sample.groups.uiGroup
import me.tbsten.katachi.ExperimentalKatachiApi
import me.tbsten.katachi.dsl.Architecture
import me.tbsten.katachi.dsl.architecture

/**
 * The architecture of this sample, written the way a user of katachi would write it.
 *
 * The definition is split one declaration per file: `roles/<Name>Role.kt` holds one role and
 * `groups/<Name>Group.kt` holds one group, which says what it is made of by calling the role
 * functions in order. Both are extensions on `DeclarationContainerScope` — the scope that
 * `architecture { }` and `"...".group { }` share — so a role can be moved into another group
 * without touching the role's own file. This file only calls the seven group functions, so it
 * stays short no matter how many roles the app grows.
 *
 * The file *names* carry the convention, so nothing has to be written twice: a role named
 * `"UiCore"` belongs in `roles/UiCoreRole.kt`, a group named `"Gradle"` in
 * `groups/GradleGroup.kt`.
 *
 * None of those functions may be `inline`. An inlined frame reports the caller's file with a
 * line number past its end, and katachi captures the declaration site from the stack, so the
 * violation would point at a line nobody wrote. Written once here rather than repeated in
 * twenty-nine files; [ProjectArchitectureSpec] is what actually holds the line.
 *
 * Every `layout { }` is written as directories, in terms of Gradle's own vocabulary: the module
 * directory (`"ui"`, `"feature" / "*"`), the source set inside it (`mainSourceSet`) and the
 * package written out as a string. `"feature" / "*"` is the one to read first — the `*` matches
 * whichever feature module exists, and a template picks one by naming the directory with a
 * capture (`--arg feature=home --arg featurePackage=home`).
 *
 * Building this value reads nothing from disk — the `layout { }` blocks are deferred until
 * a check runs — so it is safe to hold in a top level `val`.
 *
 * [ProjectArchitectureTest] is the whole of what a user writes. [ProjectArchitectureSpec]
 * is katachi's own integration test on top of it, and asserts among other things that every
 * declaration's `declaredAt` points at the file it is actually written in — not at this one
 * — which is how the sample notices if capturing the declaration site ever breaks.
 *
 * `baseline()` holds back the violations recorded in `katachi-baseline.json`
 * (declared by `roles/BaselineFileRole.kt`). Two are left in on purpose, as the demo of it:
 * `HomeFormatter.kt` in `:feature:home` and the `legacy` package of `:data`.
 */
@OptIn(ExperimentalKatachiApi::class)
val projectArchitecture: Architecture = architecture {
    title = "katachi-sample-android"
    description = "An Android app written in Compose, described by its shape with katachi. " +
        "Everything below this page is generated by `katachiDocs` and is never written by hand."
    baseline()

    featureGroup()
    uiGroup()
    dataGroup()
    appGroup()
    testingGroup()
    gradleGroup()
    toolGroup()
}
