package me.tbsten.katachi.intellij

import com.intellij.ide.starter.di.di
import com.intellij.ide.starter.path.GlobalPaths
import org.kodein.di.DI
import org.kodein.di.bindSingleton
import java.nio.file.Files
import java.nio.file.Path
import java.util.concurrent.TimeUnit
import kotlin.io.path.writeText

/** Runtime fixtures belong only to a fresh sample copy. No git commands are needed. */
internal class EditorEntryFixture(private val sample: Path, val workDir: Path) {
    lateinit var project: Path
        private set

    fun prepare(): Path {
        Files.createDirectories(workDir)
        // Each run copies the IDE (GBs); drop what earlier runs left so the disk does not fill up.
        Files.newDirectoryStream(workDir).use { dirs ->
            dirs.filter { it.fileName.toString().let { n -> n.startsWith("ide-") || n.startsWith("repository-") } }
                .forEach { it.toFile().deleteRecursively() }
        }
        val starter = workDir.resolve("starter")
        di = DI {
            extend(di)
            bindSingleton<GlobalPaths>(overrides = true) { object : GlobalPaths(starter) {} }
        }
        // A new directory prevents stale IDE workspace state (especially an already open tool window).
        val repository = Files.createTempDirectory(workDir, "repository-")
        run("rsync", "-a", *REPOSITORY_COPY_EXCLUDES, "${sample.resolve("../..").normalize()}/", "$repository/")
        project = repository.resolve("sample/jvm")
        // Two templates exercise the group → role → template hierarchy. The required body
        // parameter cannot be reverse-captured and receives the dialog's initial keyboard focus.
        project.resolve("architecture-test/src/test/kotlin/com/example/roles/ServiceRole.kt").writeText(SERVICE_ROLE)
        val service = project.resolve(SERVICE_DIR)
        Files.createDirectories(service)
        service.resolve("EntryExistingService.kt").writeText("package com.example.service\n\nclass EntryExistingService\n")
        service.resolve("EntrySettingsService.kt").writeText("package com.example.service\n\nimport kotlin.String\n\nclass EntrySettingsService\n")
        service.resolve("EntryEmptyService.kt").writeText(EMPTY_CONTENT)
        Files.createDirectories(project.resolve("src/main/resources"))
        return project
    }

    fun appBundle(contents: Path): Path {
        val bundle = Files.createTempDirectory(workDir, "ide-").resolve("IntelliJ IDEA.app")
        Files.createDirectories(bundle)
        run("ditto", contents.toString(), bundle.resolve("Contents").toString())
        return bundle
    }

    /** Includes file bytes and directories, excludes only IDE/Gradle's transient state. */
    fun sourceSnapshot(): Map<String, String> = Files.walk(project).use { paths ->
        paths.filter { path ->
            project.relativize(path).none { it.toString() in setOf(".idea", ".gradle", ".kotlin", "build") }
        }.iterator().asSequence().associate { path ->
            project.relativize(path).toString() to if (Files.isDirectory(path)) "directory" else {
                java.util.Base64.getEncoder().encodeToString(Files.readAllBytes(path))
            }
        }
    }

    private fun run(vararg command: String) {
        val process = ProcessBuilder(*command).directory(workDir.toFile()).inheritIO().start()
        if (!process.waitFor(5, TimeUnit.MINUTES)) {
            process.destroyForcibly()
            error("Timed out: ${command.first()}")
        }
        check(process.exitValue() == 0) { "Failed: ${command.joinToString(" ")}" }
    }

    companion object {
        const val SERVICE_DIR = "src/main/kotlin/com/example/service"
        const val TEMPLATE = "domain.Service.main"
        const val EMPTY_CONTENT = "  \npackage com.example.service\n\n// Placeholder\n/* Generate here. */\n  "
        fun content(name: String) = "package com.example.service\n\n// Generated by the editor entry\nclass ${name}Service\n"

        private val SERVICE_ROLE = """
            @file:OptIn(ExperimentalKatachiApi::class)

            package com.example.roles

            import com.example.modulePackage
            import me.tbsten.katachi.ExperimentalKatachiApi
            import me.tbsten.katachi.dsl.DeclarationContainerScope
            import me.tbsten.katachi.dsl.gradle.div
            import me.tbsten.katachi.dsl.gradle.kotlin
            import me.tbsten.katachi.dsl.gradle.mainSourceSet
            import me.tbsten.katachi.dsl.gradle.module
            import me.tbsten.katachi.dsl.kotlin.ktFile
            import me.tbsten.katachi.dsl.template

            fun DeclarationContainerScope.service() = "Service" {
                layout {
                    ":".module {
                        mainSourceSet / kotlin / modulePackage / "service" /
                            "${'$'}{capture("name")}Service".ktFile().template(id = "main", title = "Service source") {
                                val name = captureValue("name")
                                val body by stringParameter()
                                "package com.example.service\n\n// ${'$'}{body}\nclass ${'$'}{name}Service\n"
                            }
                        mainSourceSet / kotlin / modulePackage / "service" /
                            "${'$'}{capture("name")}Helper".ktFile().template(id = "helper", title = "Helper source") {
                                val name = captureValue("name")
                                "package com.example.service\n\nclass ${'$'}{name}Helper\n"
                            }
                    }
                }
            }
        """.trimIndent()
    }
}
