@file:OptIn(ExperimentalKatachiApi::class)

package com.example.kmp.roles

import com.example.kmp.forbiddenContents
import me.tbsten.katachi.ExperimentalKatachiApi
import me.tbsten.katachi.dsl.DeclarationContainerScope
import me.tbsten.katachi.dsl.gradle.div
import me.tbsten.katachi.dsl.gradle.kotlin
import me.tbsten.katachi.dsl.gradle.sourceSet
import me.tbsten.katachi.dsl.kotlin.ktFile
import me.tbsten.katachi.dsl.template

/**
 * The interface through which the app touches data: the `user` package of `:data`.
 *
 * There is no `settings` package beside it. Unlike sample/android this sample has no
 * SettingsRepository, and the settings screen reads `:data` through UserRepository and
 * `platformName()`.
 */
fun DeclarationContainerScope.repositoryInterface() = "RepositoryInterface" {
    title = "Repository interface"
    summary = "The :data module's user package. The interface through which the app reads data"
    description = """
        The interface through which the app touches data. It goes in the `user` package of
        `:data` as `*Repository.kt`. The caller (the ViewModel) depends only on this interface,
        and the implementation is the neighboring RepositoryImplementation role.

        The interface and its implementation are two roles because they are two kinds of file:
        one is the contract the caller reads, the other is code that may be replaced without the
        caller noticing. Their file names differ too, and a partial-match capture like `*` does
        not cross the string that follows it, so one pattern could not cover both anyway.

        The file declaration carries one `.template`. Running
        `--arg template=data.RepositoryInterface --arg name=Cache` creates only the interface
        (the implementation is generated by `data.RepositoryImplementation`, or both at once by
        giving the two ids comma-separated).

        Only `commonMain` is declared. What changes its implementation per platform is taken on
        by the neighboring ExpectDeclaration and ActualImplementation roles, not by this role.
        Adding `androidMain` here would scatter the same "absorbing platform differences" over
        two places.

        Unlike sample/android, this sample has no repository for settings. The settings screen
        is served by just reading `UserRepository` and `platformName()`. Writing an unused
        package in the definition would make the documentation point at a directory that does not exist.
    """.trimIndent()
    forbiddenContents = """
        - UI types. `UiState` lives in the core package of `:ui`, and `:data` does not know about it
        - Implementations. They belong to the RepositoryImplementation role
    """.trimIndent()
    example("UserRepository", "The interface that fetches users")
    //   ./gradlew :architecture-test:katachiTemplate --arg template=data.RepositoryInterface \
    //       --arg name=Cache
    layout {
        "data" {
            "commonMain".sourceSet / kotlin / "com/example/kmp/data" / "user" {
                "${capture("name")}Repository".ktFile()
                    .template {
                        val name = captureValue("name")
                        val item by stringParameter(default = "String")
                        """
                            package com.example.kmp.data.user

                            /** Reads ${name.lowercase()} data. */
                            interface ${name}Repository {
                                fun items(): List<$item>
                            }
                        """.trimIndent() + "\n"
                    }
            }
        }
    }
}
