package me.tbsten.katachi.dokka.llms

import me.tbsten.katachi.dokka.llms.LlmsTxtWriter.Companion.featuredItems
import me.tbsten.katachi.dokka.llms.LlmsTxtWriter.Companion.header
import me.tbsten.katachi.dokka.llms.LlmsTxtWriter.Companion.item
import me.tbsten.katachi.dokka.llms.LlmsTxtWriter.Companion.summaryOf
import me.tbsten.katachi.dokka.llms.markdown.SignatureText

/**
 * Writes the `llms-full.txt` of a module, a package or a type: the same index as its `llms.txt`,
 * with each declaration's signature and KDoc as Markdown and a link to its page.
 *
 * - A module or a package lists every type, top-level function and top-level property in it.
 *   A type's members follow it as one line each: the signature and the summary.
 * - A type gives its own KDoc, then each member in full. Nested types are only linked: each has
 *   an `llms-full.txt` of its own, and repeating them here would repeat them at every level.
 *
 * Packages matched by `optionalPackagePatterns` come last in a module's file, but are not left
 * out: this file is for readers that want everything.
 *
 * Headings nest below the `#` title: `##` for the packages of a module, then the declarations one
 * level below the section they are in. Headings inside a KDoc are pushed below the heading of the
 * section the KDoc is embedded in, so that a reader splitting the file by headings never finds a
 * KDoc's `## Example` among the packages.
 */
internal class LlmsFullTxtWriter(private val featuredTitle: String) {
    fun write(scope: LlmsScope, links: LlmsLinks): String {
        val blocks = buildList {
            add("<SYSTEM>This is the full API reference for the ${scopeName(scope)}, generated by Dokka.</SYSTEM>")
            add(header(scope, links).trim())
            when (scope) {
                is LlmsModule -> addAll(moduleBlocks(scope, links))
                is LlmsPackage -> addAll(packageBlocks(scope, links, depth = 1))
                is LlmsDeclaration -> addAll(typeBlocks(scope, links))
            }
        }
        return blocks.filter { it.isNotBlank() }.joinToString("\n\n") + "\n"
    }

    private fun moduleBlocks(module: LlmsModule, links: LlmsLinks): List<String> = buildList {
        val featured = featuredItems(module.featured, links)
        if (featured.isNotEmpty()) {
            add("## $featuredTitle")
            add(featured.joinToString("\n"))
        }
        module.packages.forEach { pkg ->
            add("## Package ${pkg.name}")
            addAll(packageBlocks(pkg, links, depth = 2))
        }
    }

    /** The package's KDoc and its declarations, under a heading of level [depth]. */
    private fun packageBlocks(pkg: LlmsPackage, links: LlmsLinks, depth: Int): List<String> = buildList {
        add(links.documentationFor(pkg.target, headingDepth = depth).of(pkg.documentation))
        (pkg.types + pkg.functions + pkg.properties).forEach { addAll(declarationBlocks(it, links, depth + 1)) }
    }

    private fun declarationBlocks(declaration: LlmsDeclaration, links: LlmsLinks, depth: Int): List<String> = buildList {
        add("${"#".repeat(depth)} ${declaration.kind} ${declaration.name}")
        addAll(bodyBlocks(declaration, links, depth))
        if (declaration.members.isNotEmpty()) {
            add("${"#".repeat(depth + 1)} Members")
            add(declaration.members.joinToString("\n") { memberItem(it, links) })
        }
    }

    private fun typeBlocks(type: LlmsDeclaration, links: LlmsLinks): List<String> = buildList {
        addAll(bodyBlocks(type, links, depth = 1))
        MemberSection.entries.forEach { section ->
            val declarations = section.of(type)
            if (declarations.isEmpty()) return@forEach
            add("## ${section.title}")
            if (section == MemberSection.Types) {
                add(declarations.distinctBy { it.target }.joinToString("\n") { item(it, links) })
            } else {
                declarations.forEach { member ->
                    add("### ${member.kind} ${member.name}")
                    addAll(bodyBlocks(member, links, depth = 3))
                }
            }
        }
    }

    /** The signature, the deprecation, the KDoc and the page of [declaration], under level [depth]. */
    private fun bodyBlocks(declaration: LlmsDeclaration, links: LlmsLinks, depth: Int): List<String> = buildList {
        declaration.signature?.let { add("```kotlin\n$it\n```") }
        if (declaration.deprecated) add("**Deprecated**")
        add(links.documentationFor(declaration.target, headingDepth = depth).of(declaration.documentation))
        links.of(declaration.target)?.let { add("Page: [${declaration.name}]($it)") }
    }

    private fun memberItem(member: LlmsDeclaration, links: LlmsLinks): String {
        val signature = member.signature?.let(SignatureText::oneLine) ?: member.name
        val code = if (signature.contains('`')) "`` $signature ``" else "`$signature`"
        val label = links.of(member.target)?.let { "[$code]($it)" } ?: code
        val summary = summaryOf(member, links)
        return if (summary.isEmpty()) "- $label" else "- $label: $summary"
    }

    private fun scopeName(scope: LlmsScope): String = when (scope) {
        is LlmsModule -> "${scope.name} module"
        is LlmsPackage -> "${scope.name} package"
        is LlmsDeclaration -> "${scope.kind} ${scope.name}"
    }
}
