package com.example.kmp

import com.example.kmp.groups.appGroup
import com.example.kmp.groups.dataGroup
import com.example.kmp.groups.featureGroup
import com.example.kmp.groups.gradleGroup
import com.example.kmp.groups.testingGroup
import com.example.kmp.groups.toolGroup
import com.example.kmp.groups.uiGroup
import me.tbsten.katachi.ExperimentalKatachiApi
import me.tbsten.katachi.dsl.Architecture
import me.tbsten.katachi.dsl.architecture

/**
 * The architecture of this sample, described with katachi.
 *
 * Every role declares the paths it may occupy in its own `layout { }`. A Gradle module is
 * written as its directory (`"data"`, `"app/android"`, `"feature" / "*"`), a source set as
 * `"commonMain".sourceSet`, and the package below it as a string, so that the definition says
 * what the build says.
 *
 * `files` is not set, so the default `gitTracked()` applies, and it does the work: `build/`,
 * `.kotlin/` and `local.properties` are never offered to the check, so no role has to claim
 * them. This sample is a directory of the katachi repository rather than a repository of its
 * own — its project root is the directory holding its own `gradlew`, and the `.git` is two
 * levels above — but that changes nothing, because katachi asks git whether the root is
 * inside a work tree rather than looking for a `.git` beside it.
 *
 * Kept in a top level `val`: building it reads nothing and runs no check, so the same value
 * can be shared by every test and by `katachiDocs`, which generates `docs/` from it.
 *
 * This file does nothing but call the seven group functions. The definition itself is split
 * one declaration per file: a role named `"UiCore"` is declared in the `roles` package, in
 * `UiCoreRole.kt`, and a group named `"Gradle"` in the `groups` package, in `GradleGroup.kt`.
 * The file name is the whole of the convention, so nothing has to be written down twice.
 *
 * Both kinds are plain `DeclarationContainerScope` extension functions — the scope
 * `architecture { }` and `"...".group { }` share — so a role can be moved into another group
 * without its own file being touched.
 *
 * None of them may be `inline`. An inlined frame reports the caller's file with a line number
 * remapped past the end of that file, and katachi captures the declaration site from the
 * stack, so every declaration would record a position nobody wrote. Written once here rather
 * than repeated in twenty-nine files; `ProjectArchitectureSpec` is what actually holds the
 * line, by reading the captured line back out of the source.
 *
 * `baseline()` holds back the violations recorded in `katachi-baseline.json`
 * (declared by `roles/BaselineFileRole.kt`). One is left in on purpose, as the demo of it: the
 * `user` directory in `androidMain` of `:data`.
 */
@OptIn(ExperimentalKatachiApi::class)
val projectArchitecture: Architecture = architecture {
    title = "katachi-sample-kmp"
    description = "A Kotlin Multiplatform app (Android and iOS), described by its shape with katachi. " +
        "Everything below this page is generated by `katachiDocs` and is never written by hand."
    baseline()

    featureGroup()
    uiGroup()
    dataGroup()
    testingGroup()
    appGroup()
    gradleGroup()
    toolGroup()
}
