package me.tbsten.katachi.intellij.presentation

/** The Japanese wording of the screen spec (`.local/design-ide-plugin`), the source [EnglishKatachiStrings] follows. */
internal object JapaneseKatachiStrings : KatachiStrings {
    override val initializing = "定義モジュールを探しています"
    override val loadingTitle = "テンプレートを読み込んでいます"
    override val loadingNote = "初回は定義のコンパイルがあるため、数十秒かかることがあります。"
    override val cancel = "キャンセル"
    override val showLog = "ログを見る"
    override val reload = "再読み込み"
    override val sync = "同期する"
    override val details = "詳細"
    override fun refreshing(since: String) = "更新中…（前回: $since）"
    override fun minutesAgo(minutes: Long) = "${minutes}分前"
    override fun hoursAgo(hours: Long) = "${hours}時間前"
    override fun daysAgo(days: Long) = "${days}日前"
    override val justNow = "たった今"

    override val noTemplatesTitle = "テンプレートがまだありません"
    override val noTemplatesBody = "役割に template { } を書くと、ここに並びます。"
    override val howToWrite = "書き方を見る"
    override val notGradleTitle = "Gradle プロジェクトではありません"
    override val notGradleBody = "katachi のテンプレートは、Gradle の定義モジュールから読み込みます。"
    override val notSyncedTitle = "Gradle の同期が済んでいません"
    override val notSyncedBody = "同期が終わると、自動で探し直します。"
    override val notInstalledTitle = "katachi が見つかりません"
    override val notInstalledBody =
        "定義モジュールに katachi の Gradle プラグインを適用してください。適用した直後なら、Gradle を同期してください。"
    override val installGuide = "導入手順を見る"
    override fun outdatedTitle(version: String?) =
        if (version == null) "katachi を更新してください（0.2 以降）" else "katachi を更新してください（いま $version、0.2 以降が必要）"

    override val outdatedBody = "この版の katachi は、IDE 用のタスクを持っていません。"
    override val updateGuide = "更新手順を見る"
    override fun searchEmptyTitle(query: String) = "「$query」に一致するテンプレートはありません"
    override val clearSearch = "検索をクリア"

    override val loadErrorTitle = "テンプレートを読み込めませんでした"
    override val compileFailed = "定義モジュールのコンパイルに失敗しました。"
    override val compileFailedHint = "定義を直してから再読み込みしてください。"
    override val staleSync = "Gradle の同期が古い可能性があります。"
    override val staleSyncHint = "Gradle を同期してから再読み込みしてください。"
    override val architectureNotSet = "定義モジュールに katachi { architecture = ... } がありません。"
    override val architectureNotSetHint = "build.gradle.kts に architecture を設定してください。"
    override val openBuildScript = "build.gradle.kts を開く"
    override val gradleFailed = "Gradle の実行に失敗しました。"
    override val gradleFailedHint = "詳細にログの最後の数行を出しています。"
    override val jsonMissing = "テンプレートの一覧（JSON）が書かれませんでした。"
    override val jsonMalformed = "テンプレートの一覧（JSON）を読めませんでした。"
    override val jsonIncompatible = "katachi とプラグインの版の組み合わせが合いません。"
    override val jsonIncompatibleHint = "katachi とプラグインを、どちらも最新にしてください。"
    override val openJson = "JSON を開く"
    override val loadCancelled = "読み込みを止めました"
    override val staleListBanner = "読み込めませんでした。前回の一覧を出しています。"
    override val definitionChanged = "定義が変わりました。"
    override fun removedTemplates(names: List<String>) = "${names.joinToString("、")} は無くなりました"

    override val searchPlaceholder = "検索"
    override val outsideSearch = "検索外・選択中"
    override fun filledCount(filled: Int, total: Int) = "入力済み $filled/$total"
    override val previewFailed = "プレビューに失敗しました。⋯ の「原因を見る」で理由を確かめられます。"
    override fun unknownKinds(kinds: List<String>) =
        "このプラグインが知らない型の引数があります（${kinds.joinToString()}）"

    override val unresolvedTarget = "生成先の決まらないファイルがあります"
    override val copyCommand = "コマンドをコピー"
    override val showCause = "原因を見る"
    override val causeLoading = "原因を調べています…"

    override fun collapsedField(name: String, controller: String, value: String): String {
        val label = valueLabel(value)
        // Latin values get spaces around them, as Japanese text around code does elsewhere.
        return if (label == value) "$name（$controller が $label のとき）" else "$name（$controller が${label}のとき）"
    }

    override fun valueLabel(value: String) = when (value) {
        "true" -> "オン"
        "false" -> "オフ"
        else -> value
    }

    override val chooseOne = "選んでください"
    override val requiredError = "入力してください"
    override fun notAnInt(min: Int, max: Int) = "整数で入力してください（$min〜$max）"
    override val notAccepted = "候補から選んでください"
    override fun capturePathHint(name: String, markedPattern: String) = "生成先 $markedPattern の <$name> に入るディレクトリ名"
    override fun captureModuleHint(name: String, markedPattern: String) = "モジュール $markedPattern の <$name> に入る、既存のモジュール名"
    override fun captureModuleTarget(path: String) = "生成先 $path"
    override fun notAnExistingModule(existing: List<String>) =
        if (existing.isEmpty()) "当てはまるモジュールがありません" else "今あるモジュールから選んでください（${existing.joinToString(", ")}）"
    override val captureSeparatorError = "1階層の名前にしてください（/ と \\ は使えません）"
    override val captureDotError = ". や .. は使えません"
    override val multilineOn = "複数行で入力"
    override val multilineOff = "1行に戻す"
    override val alreadyExists = "既にある"

    override val nothingSelected = "テンプレートにチェックを入れてください"
    override fun reasonRequired(role: String, parameter: String) = "$role: $parameter が未入力です"
    override fun reasonNotAnInt(role: String, parameter: String) = "$role: $parameter は整数で入力してください"
    override fun reasonNotAccepted(role: String, parameter: String) = "$role: $parameter の値が候補にありません"
    override fun reasonInvalidCapture(role: String, capture: String) = "$role: $capture は1階層のディレクトリ名にしてください"
    override fun reasonNotExistingModule(role: String, capture: String) = "$role: $capture に当たるモジュールがありません"
    override fun reasonUnavailable(role: String) = "$role は生成できません"
    override fun reasonUnresolved(role: String, fileName: String) = "$role: $fileName の生成先が決まりません"
    override val reasonGenerating = "生成しています"
    override val reasonLoading = "テンプレートを読み込んでいます"
    override val onExisting = "既存ファイル"
    override val onExistingAsk = "確認する"
    override val onExistingSkip = "スキップ"
    override val onExistingOverwrite = "上書き"
    override val overwriteWarning = "既存ファイルを確認なしで置き換えます"
    override val generate = "生成"

    override fun rowWritten(count: Int) = if (count == 1) "1 file" else "$count files"
    override fun rowRunning(taskPath: String?) = if (taskPath == null) "実行中" else "実行中 > $taskPath"
    override val rowWaiting = "待ち"
    override val rowAwaitingConflict = "既にあるファイル · 確認待ち"
    override fun runningTask(taskPath: String) = "› $taskPath"
    override val noArguments = "（引数なし）"
    override fun generatingProgress(position: Int, total: Int) = "生成しています… $position / $total"
    override val waitingForLoad = "読み込みの完了を待っています…"
    override val waitingForConflict = "確認を待っています…"
    override val fileNew = "新規"
    override val fileOverwritten = "上書き"
    override val fileSkipped = "スキップ"
    override val openedMarker = "← Opened"
    override val rowSkipped = "既にあるファイルがあるので、書きませんでした"
    override val rowStopped = "ここで止めました（既にあるファイルがあります）"
    override val rowInterrupted = "中断（書かれたかは不明）"
    override val rowNotRun = "未実行"
    override val writesUnknown = "生成済み（書いたファイルは不明）"
    override val outputIncomplete = "生成済み（出力が不完全）"
    override val definitionCompileFailed = "定義のコンパイルに失敗しました"
    override val generationTaskNotFound = "タスクが見つかりません。Gradle の同期が古い可能性があります"
    override fun resultAll(count: Int) = "$count 件を生成しました"
    override fun resultPartial(done: Int, total: Int) = "$total 件中 $done 件を生成（書いたファイルは残る）"
    override fun resultNothingWritten(total: Int) = "$total 件中 0 件を生成（何も書いていません）"
    override fun undoHint(label: String) = "戻す: Local History「$label」"
    override val retryRemaining = "残りをやり直す"
    override val continueGenerating = "続けて生成"
    override val uncheckAll = "チェックを外す"
}
