package me.tbsten.katachi.test.synthetic

import java.io.File
import me.tbsten.katachi.dsl.files.KatachiFileSystem
import me.tbsten.katachi.dsl.files.internal.RealFileSystem

/**
 * Writes this project into [directory] as real files, and returns a file system rooted there.
 *
 * For checks that read contents, which the in-memory tree cannot give: Konsist parses every
 * `.kt` file it is pointed at. Each `.kt` file declares one small class in a package named after
 * its directory, so the files parse and no two declare the same name. `.git/HEAD` is written too,
 * as the project root marker.
 *
 * [directory] is used as the project root as it is: pass an empty one, such as a fresh temporary
 * directory. The returned file system starts its project root search in [directory], not in the
 * JVM's working directory.
 */
fun SyntheticProject.writeTo(directory: File): KatachiFileSystem {
    for (path in files + GIT_MARKER) {
        val file = File(directory, path)
        file.parentFile.mkdirs()
        file.writeText(contentOf(path))
    }
    return RealFileSystem(directory.absoluteFile)
}

private fun contentOf(path: String): String {
    val name = path.substringAfterLast('/')
    return when {
        name.endsWith(".kt") -> kotlinSourceOf(path, name.removeSuffix(".kt"))
        name.endsWith(".kts") -> "// Generated by generateProject().\n"
        else -> "generated\n"
    }
}

private fun kotlinSourceOf(path: String, className: String): String {
    val packageName = "synthetic." + path.substringBeforeLast('/').substringAfterLast('/')
    return """
        package $packageName

        class $className {
            val id: Int = ${className.hashCode()}

            fun describe(): String = "$className#${'$'}id"
        }
    """.trimIndent() + "\n"
}
