package com.example

import io.kotest.core.spec.style.FreeSpec
import io.kotest.matchers.shouldBe
import java.io.File
import me.tbsten.katachi.ExperimentalKatachiApi
import me.tbsten.katachi.InternalKatachiApi
import me.tbsten.katachi.check.internal.moduleIndex
import me.tbsten.katachi.dsl.LayoutEntry
import me.tbsten.katachi.dsl.files.internal.RealFileSystem
import me.tbsten.katachi.dsl.files.internal.findProjectRoot
import me.tbsten.katachi.dsl.internal.flattenLayout

/**
 * katachi's own self-verification, not part of adopting katachi: a sentinel that records what
 * this sample's `layout { }` blocks flatten to, so that rewriting a role is only accepted when
 * it still checks the same tree.
 *
 * The snapshot lives **inside** the sample, at `snapshots/layout.txt`, and is declared by the
 * `testing/LayoutSnapshot` role -- the same arrangement `docs/` has. Everything inside the
 * sample is subject to its own allow list, so a generated file that is not `build/` needs a
 * role; putting it outside the project root would only move that cost somewhere else.
 *
 * `flattenLayout()` is `@InternalKatachiApi` and the [LayoutEntry] it returns is
 * `@ExperimentalKatachiApi` — a user asserts and never reads the entries — so this file opts in
 * to both where a user would not have to.
 */
@OptIn(InternalKatachiApi::class, ExperimentalKatachiApi::class)
class LayoutSnapshotSpec : FreeSpec({
    "the flattened layout matches the recorded snapshot" {
        val actual = renderSnapshot(flattenCurrentLayout())
        val file = snapshotFile()

        when {
            updateRequested() -> file.write(actual)
            !file.isFile -> {
                file.write(actual)
                throw AssertionError(
                    "${file.path} did not exist, so it was created with the current content. Review the diff and run again.",
                )
            }
            // Compared as one text rather than line by line: the header is generated together
            // with the body, so an update never leaves the two out of step.
            else -> actual shouldBe file.readText()
        }
    }

    "the snapshot has at least one entry" {
        // A layout that flattened to nothing would match an empty snapshot forever. This is
        // the one thing the comparison above cannot notice by itself.
        flattenCurrentLayout().isNotEmpty() shouldBe true
    }
})

/** Set to `true` to rewrite the snapshot instead of comparing against it. */
private const val UPDATE_PROPERTY: String = "katachi.snapshot.update"

/** Where the snapshot lives, relative to this sample's project root. */
private const val SNAPSHOT_PATH: String = "snapshots/layout.txt"

/**
 * The header written into the snapshot, so the file says how to regenerate itself.
 */
private val HEADER: List<String> = listOf(
    "# Snapshot for katachi's own sample self-verification. Do not edit by hand.",
    "# Generated by: LayoutSnapshotSpec in sample/custom-processor " +
        "(the result of projectArchitecture.flattenLayout())",
    "# Update: cd sample/custom-processor && " +
        "./gradlew :architecture-test:test -D$UPDATE_PROPERTY=true",
    "# One line = <role qualifiedName> TAB <path> TAB <kind> TAB <required|optional>",
)

private fun updateRequested(): Boolean = System.getProperty(UPDATE_PROPERTY) == "true"

private fun File.write(text: String) {
    parentFile.mkdirs()
    writeText(text)
}

/**
 * The layout as the check sees it.
 *
 * The module index is built from the real tree, because this definition names modules with
 * `":".module { }` and `":architecture-test".module { }` and those keys are what it resolves.
 * Recording the snapshot without it would compare two different questions.
 */
@OptIn(InternalKatachiApi::class, ExperimentalKatachiApi::class)
private fun flattenCurrentLayout(): List<LayoutEntry> {
    val fileSystem = RealFileSystem()
    val projectRoot = findProjectRoot(fileSystem)
    val modules = moduleIndex(fileSystem, projectRoot.path, projectArchitecture.moduleResolver)
    return projectArchitecture.flattenLayout(modules)
}

/**
 * Renders the entries in an order that depends on nothing but the entries themselves.
 *
 * Declaration order is deliberately dropped: reordering the roles changes nothing about what
 * the check accepts.
 */
@OptIn(InternalKatachiApi::class, ExperimentalKatachiApi::class)
private fun renderSnapshot(entries: List<LayoutEntry>): String {
    val lines = entries
        .map { entry ->
            val requirement = if (entry.required) "required" else "optional"
            "${entry.role.qualifiedName}\t${entry.path}\t${entry.kind}\t$requirement"
        }
        .sorted()
    return (HEADER + lines).joinToString(separator = "\n", postfix = "\n")
}

/**
 * `sample/custom-processor/snapshots/layout.txt`, located through katachi's own project-root
 * detection rather than by counting `..` from the working directory.
 */
@OptIn(InternalKatachiApi::class, ExperimentalKatachiApi::class)
private fun snapshotFile(): File =
    File(File(findProjectRoot(RealFileSystem()).path.value), SNAPSHOT_PATH)
