package me.tbsten.katachi.gradle;

import java.util.Map;
import java.util.TreeMap;

/**
 * Builds the text of the Kotlin source {@link GenerateKatachiEntryPointTask} writes.
 *
 * <p>A plain function of its inputs and nothing else -- no file IO, no Gradle types -- so the
 * generated text can be pinned down with a fast JUnit test
 * ({@code KatachiEntryPointSourceTest}) instead of only through a slow, Gradle-driven functional
 * test.
 *
 * <p>Only {@code architecture} is referenced through an {@code import}; every processor class is
 * written fully qualified inside the {@code mapOf(...)} literal. Importing the architecture is
 * what buys the compile-time guarantee this whole design is for -- a wrong FQCN, or a value that
 * is not an {@code Architecture}, fails {@code compileTestKotlin} rather than failing at run
 * time. Importing every processor class too would only raise the odds of two processors sharing
 * a simple name colliding, for no benefit: nothing about a processor's own type is checked here,
 * only that {@code register(...)} was pointed at a syntactically plausible class name --
 * {@link KatachiProcessors#register} already refused anything else at configuration time.
 */
final class KatachiEntryPointSource {

    /** The package the generated file declares. */
    private static final String PACKAGE_NAME = "me.tbsten.katachi.generated";

    /** The generated object's simple name. */
    private static final String SIMPLE_NAME = "GeneratedKatachiEntryPoint";

    /** The generated object's fully qualified name, what {@code --entry-point} is given. */
    static final String QUALIFIED_NAME = PACKAGE_NAME + "." + SIMPLE_NAME;

    /** Where the generated file is written, relative to the task's output directory. */
    static final String RELATIVE_PATH = "me/tbsten/katachi/generated/" + SIMPLE_NAME + ".kt";

    private KatachiEntryPointSource() {
    }

    /**
     * Renders the Kotlin source of {@code GeneratedKatachiEntryPoint}.
     *
     * @param architectureClassName the fully qualified name of the top level {@code val
     *     Architecture} to import and expose as {@code architecture}.
     * @param processors every registered processor, key to fully qualified class name. Rendered
     *     sorted by key, so that reordering registrations in a build script does not change the
     *     generated text.
     */
    static String render(
            String architectureClassName,
            Map<String, String> processors) {
        Map<String, String> sorted = new TreeMap<>(processors);

        StringBuilder out = new StringBuilder();
        out.append(
                "// Generated by the katachi Gradle plugin from the `katachi { }` block of this "
                        + "module's\n");
        out.append(
                "// build.gradle.kts. Do not edit: every `runKatachiProcessor` run overwrites "
                        + "it.\n");
        out.append("@file:Suppress(\"RedundantVisibilityModifier\", \"unused\")\n");
        // Both walls, not just the internal one. `KatachiEntryPoint` itself and every
        // processor a user is likely to register (`LayoutCheck`, `KonsistCheck`) carry
        // `@ExperimentalKatachiApi`, whose level is ERROR -- the file this writes would not
        // compile in the user's own test compilation without it.
        out.append(
                "@file:OptIn(me.tbsten.katachi.InternalKatachiApi::class,"
                        + " me.tbsten.katachi.ExperimentalKatachiApi::class)\n");
        out.append("\n");
        out.append("package ").append(PACKAGE_NAME).append("\n");
        out.append("\n");
        out.append("import ").append(architectureClassName).append("\n");
        out.append("\n");
        // `HIDDEN` takes the object out of Kotlin's source-level resolution while leaving the
        // bytecode untouched, so it stops appearing in the user's autocomplete without stopping
        // `Class.forName(...).getDeclaredField("INSTANCE")` from reading it. Nothing in any
        // Kotlin source refers to this object by name -- `runKatachiProcessor` hands its
        // fully qualified name to `main()` as a string -- so there is nothing left for hiding
        // it to break.
        out.append(
                "@Deprecated(\n"
                        + "    \"Generated by the katachi Gradle plugin. `runKatachiProcessor` "
                        + "loads it by name; do not reference it.\",\n"
                        + "    level = DeprecationLevel.HIDDEN,\n"
                        + ")\n");
        out.append("public object ").append(SIMPLE_NAME)
                .append(" : me.tbsten.katachi.processor.internal.KatachiEntryPoint {\n");
        String architectureSimpleName = architectureClassName.substring(architectureClassName.lastIndexOf('.') + 1);
        out.append("    public override val architecture: me.tbsten.katachi.dsl.Architecture = ")
                .append(architectureSimpleName)
                .append("\n");
        out.append("\n");
        if (sorted.isEmpty()) {
            out.append("    public override val processors: Map<String, Class<*>> = emptyMap()\n");
        } else {
            out.append("    public override val processors: Map<String, Class<*>> = mapOf(\n");
            for (Map.Entry<String, String> entry : sorted.entrySet()) {
                out.append("        \"").append(entry.getKey()).append("\" to ")
                        .append(entry.getValue()).append("::class.java,\n");
            }
            out.append("    )\n");
        }
        out.append("}\n");
        return out.toString();
    }
}
