package me.tbsten.katachi.test.dokka

import io.kotest.core.spec.style.FreeSpec
import io.kotest.matchers.collections.shouldContainExactly
import io.kotest.matchers.ints.shouldBeLessThan
import io.kotest.matchers.nulls.shouldNotBeNull
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain
import io.kotest.matchers.string.shouldMatch
import io.kotest.matchers.string.shouldStartWith

class LlmsFullTxtSpec : FreeSpec({
    val full by lazy {
        DokkaRunner.run(
            LlmsSources.SHOP,
            DokkaRunner.configuration(moduleName = "shop", includes = listOf(LlmsSources.INCLUDES)),
        ).files["llms-full.txt"].shouldNotBeNull()
    }

    "SYSTEM の行とタイトルで始まる" {
        full shouldStartWith
            "<SYSTEM>This is the full API reference for the shop module, generated by Dokka.</SYSTEM>\n\n# shop\n"
    }

    "パッケージごとの節が並び、optional のパッケージは最後に来る" {
        Regex("^## Package (.+)$", RegexOption.MULTILINE).findAll(full).map { it.groupValues[1] }.toList() shouldContainExactly
            listOf("shop.api", "shop.internal")
    }

    "型の節には Dokka のシグネチャ、KDoc 全体、ページの Markdown 版へのリンクが入る" {
        val cart = full.substringAfter("### class Cart\n").substringBefore("\n### ")
        cart shouldContain "```kotlin\nclass Cart(val owner: String)\n```"
        cart shouldContain "```kotlin\nval cart = Cart(\"alice\")\n```"
        cart shouldContain "- **Property** `owner`: Who the cart belongs to."
        cart shouldContain "Page: [Cart](shop/shop.api/-cart/index.html.md)"
    }

    "メンバはシグネチャと概要の1行ずつで、コンストラクタも、クラスの @property で説明されたプロパティも含む" {
        val members = full.substringAfter("### class Cart\n").substringAfter("#### Members\n\n").substringBefore("\n\n")
        members.lines() shouldContainExactly listOf(
            "- [`constructor(owner: String)`](shop/shop.api/-cart/-cart.html.md)",
            "- [`fun add(item: Item): Cart`](shop/shop.api/-cart/add.html.md): Adds [item](shop/shop.api/-cart/add.html.md) to the cart.",
            "- [`val owner: String`](shop/shop.api/-cart/owner.html.md): Who the cart belongs to.",
        )
    }

    "トップレベルの関数とプロパティも、型と同じ形の節になる" {
        full shouldContain "### function checkout\n\n```kotlin\nfun checkout(cart: Cart): Receipt\n```"
        full shouldContain "### property currency\n\n```kotlin\nval currency: String\n```"
        full.indexOf("### function pay") shouldBeLessThan full.indexOf("**Deprecated**")
    }

    "KDoc の中の見出しは宣言の見出しより下の階層にずらされ、## と ### は節の見出しにしか使われない" {
        val receipt = full.substringAfter("### object Receipt\n").substringBefore("\n### ")
        receipt shouldContain "##### Example 1: keeping the receipt"
        receipt shouldContain "###### Details"
        Regex("^## (.+)$", RegexOption.MULTILINE).findAll(full).map { it.groupValues[1] }
            .filterNot { it == "Featured" }
            .forEach { it shouldStartWith "Package " }
        Regex("^### (.+)$", RegexOption.MULTILINE).findAll(full).map { it.groupValues[1] }
            .forEach { it shouldMatch DECLARATION_HEADING }
    }

    "@featured のタグ自体はどこにも出ない" {
        full shouldNotContain "@featured"
        full shouldNotContain "**featured**"
    }
})

/** `kind Name` of a declaration's section, as `LlmsFullTxtWriter` writes it. */
private val DECLARATION_HEADING = Regex("(class|interface|object|enum|annotation|typealias|function|property|constructor|enum entry) \\S+")
