package me.tbsten.katachi.test.dokka

import io.kotest.core.spec.style.FreeSpec
import io.kotest.matchers.collections.shouldContainExactly
import io.kotest.matchers.nulls.shouldNotBeNull
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain
import io.kotest.matchers.string.shouldStartWith

class LlmsDirectorySpec : FreeSpec({
    val run by lazy { DokkaRunner.run(TREE, DokkaRunner.configuration(moduleName = "tree")) }
    fun file(path: String) = run.files[path].shouldNotBeNull()

    "ディレクトリになっているページ (モジュール・パッケージ・型) のどれにも、llms.txt と llms-full.txt が並ぶ" {
        val directories = run.files.keys.filter { it == "index.html" || it.endsWith("/index.html") }
            .map { it.removeSuffix("index.html") }
        directories.flatMap { listOf("${it}llms.txt", "${it}llms-full.txt") }
            .filterNot { it in run.files } shouldContainExactly emptyList()
    }

    "パッケージの llms.txt" - {
        val llms by lazy { file("tree/tree/llms.txt") }

        "パッケージ名の見出しで始まり、配下の型と関数を名前・概要・Markdown 版へのリンクで並べる" {
            llms shouldStartWith "# tree\n"
            llms.section("Types").lines() shouldContainExactly listOf(
                "- [Outer](-outer/index.html.md): The outer type.",
                "- [Outer.Inner](-outer/-inner/index.html.md): A nested type.",
            )
            llms.section("Functions").lines() shouldContainExactly listOf("- [top](top.html.md): A top-level function.")
        }
    }

    "型の llms.txt は、メンバと入れ子の型を並べる" {
        val llms = file("tree/tree/-outer/llms.txt")
        llms shouldStartWith "# Outer\n\n> The outer type.\n"
        llms.section("Types") shouldContain "- [Outer.Inner](-inner/index.html.md): A nested type."
        llms.section("Functions") shouldContain "- [run](run.html.md): Does outer things."
    }

    "型の llms-full.txt" - {
        val full by lazy { file("tree/tree/-outer/llms-full.txt") }

        "自分の KDoc と、メンバの KDoc 全体を含む" {
            full shouldContain "```kotlin\nclass Outer\n```"
            full shouldContain "### function run\n\n```kotlin\nfun run()\n```\n\nDoes outer things.\n\nIt has a second paragraph."
        }

        "入れ子の型はリンクと概要だけで、その中身は入れ子の型の llms-full.txt に任せる" {
            full shouldContain "## Types\n\n- [Outer.Inner](-inner/index.html.md): A nested type."
            full shouldNotContain "Does inner things."
            file("tree/tree/-outer/-inner/llms-full.txt") shouldContain "Does inner things."
        }
    }

    "パッケージの llms-full.txt は、配下の型を入れ子まで含めて全部載せる" {
        val full = file("tree/tree/llms-full.txt")
        full shouldStartWith "<SYSTEM>This is the full API reference for the tree package, generated by Dokka.</SYSTEM>\n\n# tree\n"
        full shouldContain "## class Outer"
        full shouldContain "## class Outer.Inner"
        full shouldContain "## function top"
    }
})

private val TREE: String = """
    |/src/main/kotlin/tree/Outer.kt
    |package tree
    |
    |/** The outer type. */
    |public class Outer {
    |    /** A nested type. */
    |    public class Inner {
    |        /** Does inner things. */
    |        public fun work() {}
    |    }
    |
    |    /**
    |     * Does outer things.
    |     *
    |     * It has a second paragraph.
    |     */
    |    public fun run() {}
    |}
    |
    |/** A top-level function. */
    |public fun top() {}
""".trimMargin()
