package com.example

import com.example.groups.apiGroup
import com.example.groups.appGroup
import com.example.groups.dataGroup
import com.example.groups.domainGroup
import com.example.groups.gradleGroup
import com.example.groups.testingGroup
import com.example.groups.toolGroup
import me.tbsten.katachi.ExperimentalKatachiApi
import me.tbsten.katachi.dsl.Architecture
import me.tbsten.katachi.dsl.architecture

/**
 * The architecture of this sample, described with katachi.
 *
 * The definition is split one declaration per file: `roles/<Name>Role.kt` holds one role and
 * `groups/<Name>Group.kt` holds one group, which says what it is made of by calling the role
 * functions in order. Both are extensions on `DeclarationContainerScope` - the scope that
 * `architecture { }` and `"...".group { }` share - so a role can be moved into another group
 * without touching the role's own file. This file only calls the seven group functions, so it
 * stays short no matter how many roles the project grows.
 *
 * None of those functions may be `inline`. An inlined frame reports the caller's file with a
 * line number past its end, and katachi captures the declaration site from the stack, so the
 * violation would point at a line nobody wrote. Written once here rather than repeated in
 * twenty-one files; `ProjectArchitectureSpec` is what actually holds the line.
 *
 * Every role carries a `layout { }` saying where its files may live, written in terms of
 * Gradle: the application is the root project itself, `"architecture-test" / ...` is the
 * module holding this definition, `mainSourceSet` and `testSourceSet` are the source sets,
 * and the package directory is written out as a plain string. None of it is a new kind of
 * declaration — a source set is the directory `src/<name>`.
 *
 * katachi denies by default, so this is an allow list: every file in the project has to be
 * covered by some role, and anything else fails `ProjectArchitectureTest`.
 *
 * `baseline()` holds back the violations recorded in `katachi-baseline.json`
 * (declared by `roles/BaselineFileRole.kt`). Two are left in on purpose, as the demo of it: see
 * `service/LegacyHealthCheck.kt` and `service/LegacyStatusService.kt`.
 */
@OptIn(ExperimentalKatachiApi::class)
val projectArchitecture: Architecture = architecture {
    title = "Ktor sample app"
    description = "A small Ktor HTTP server, described by its shape with katachi. " +
        "Every page below this one is generated by `katachiDocs`, not written by hand."
    baseline()

    apiGroup()
    domainGroup()
    dataGroup()
    appGroup()
    testingGroup()
    gradleGroup()
    toolGroup()
}
